ALTER TABLE users
    DROP CONSTRAINT IF EXISTS chk_users_role;

UPDATE users
SET role = 'CLIENT'
WHERE role IN ('CUSTOMER', 'BARBER');

ALTER TABLE users
    ADD CONSTRAINT chk_users_role
        CHECK (role IN ('CLIENT', 'ADMIN'));

ALTER TABLE users
    ALTER COLUMN email TYPE VARCHAR(180);

ALTER TABLE users
    ALTER COLUMN password_hash TYPE VARCHAR(100);


CREATE TABLE IF NOT EXISTS barber_shops (
    id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    cep VARCHAR(8),
    street VARCHAR(160),
    number VARCHAR(20),
    neighborhood VARCHAR(120),
    city VARCHAR(120),
    state VARCHAR(2),
    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS barbers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(120) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS service_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(120) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    duration_minutes INT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id),

    CONSTRAINT ck_service_price
        CHECK (price > 0),

    CONSTRAINT ck_service_duration
        CHECK (
            duration_minutes > 0
            AND MOD(duration_minutes, 30) = 0
        )
);


CREATE TABLE IF NOT EXISTS work_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    barber_id BIGINT NOT NULL,
    day_of_week VARCHAR(16) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    PRIMARY KEY (id),

    CONSTRAINT uk_schedule_barber_day
        UNIQUE (barber_id, day_of_week),

    CONSTRAINT fk_schedule_barber
        FOREIGN KEY (barber_id)
        REFERENCES barbers (id)
);


CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    client_id BIGINT NOT NULL,
    barber_id BIGINT NOT NULL,
    service_item_id BIGINT NOT NULL,
    start_at TIMESTAMP(6) NOT NULL,
    end_at TIMESTAMP(6) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    status VARCHAR(32) NOT NULL,
    checkout_session_id VARCHAR(255),
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),

    CONSTRAINT uk_appointment_checkout
        UNIQUE (checkout_session_id),

    CONSTRAINT fk_appointment_client
        FOREIGN KEY (client_id)
        REFERENCES users (id),

    CONSTRAINT fk_appointment_barber
        FOREIGN KEY (barber_id)
        REFERENCES barbers (id),

    CONSTRAINT fk_appointment_service
        FOREIGN KEY (service_item_id)
        REFERENCES service_items (id)
);


CREATE INDEX IF NOT EXISTS idx_appointment_barber_period
    ON appointments (
        barber_id,
        start_at,
        end_at,
        status
    );

CREATE INDEX IF NOT EXISTS idx_appointment_client
    ON appointments (
        client_id,
        start_at
    );


CREATE TABLE IF NOT EXISTS stripe_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(120) NOT NULL,
    checkout_session_id VARCHAR(255),
    processed_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),

    CONSTRAINT uk_stripe_event_id
        UNIQUE (event_id)
);
