spring:
  application:
    name: barberbook-backend

  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
